[package]
name = "tsp_algos"
version = "0.1.0"
authors = ["krotera <01101011@tuta.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
howlong = "0.1"
priority-queue = "1.0"
